// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjldyutjhiytmkbukxbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qbGR5dXRqaGl5dG1rYnVreGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MTI1NjEsImV4cCI6MjA2ODE4ODU2MX0.RMpmSartkYNwuQdgZXZgCt3VYQmbdExS9SNc73IRAd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});